package me.tpcreative.audiovisualizer.visualizer

enum class EnumEvent {
    FINISH_ACTIVITY, OPEN_ACTIVITY, NONE, CONNECTED, DISCONNECTED,START,START_RECORDING_FAILED,CREATE_FOLDER_FAILED,REQUEST_STOP_RECORDING,START_PRIMARY_TIMER,STOP_PRIMARY_TIMER
}